on:
  push:
    branches:
      - '*'
      
jobs:
  notify-slack:
    runs-on: ubuntu-latest
   # needs: build-test
    steps:
      - name: Send Slack notification on release branch
        if: contains('refs/heads/release/', github.ref)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROD }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Hello,\n\nWorkflow for release branch: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"}(${{ job.status }}) triggered by ${{ github.actor }} on ${{ github.event_name }} branch: ${{ github.ref }} - <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>' \
          $SLACK_WEBHOOK_URL
          
      - name: Send Slack notification on feature branch
        if: startsWith(github.ref, 'refs/heads/feature/')
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NON_PROD }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Hello Workflow for feature branch: ${{ github.workflow }} has ${{ job.status }}."}' \
          $SLACK_WEBHOOK_URL
